let practices = [];
const YANDEX_PUBLIC_URL = "https://disk.360.yandex.ru/i/bb4_n7M_j4k5Eg";
const state = { search: "", direction: "", country: "", factor: "", international: false, selectedId: null };
const directionStyles = {
  "Работа и свое дело": { color: "#00aeef" },
  "Образование и развитие": { color: "#2b4f7c" },
  "Благоустройство": { color: "#32947d" },
  "Транспорт": { color: "#6e63a2" },
  "Укрепление и охрана здоровья": { color: "#e05555" },
  "Работа и свое дело / Образование и развитие": { color: "#9a7d2e" },
  "Транспорт / Благоустройство": { color: "#487675" },
};
const el = (id) => document.getElementById(id);
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[char]));
const getOptions = (key) => [...new Set(practices.map((item) => item[key]).filter(Boolean))].sort((a, b) => a.localeCompare(b, "ru"));
const firstUrl = (text = "") => (String(text).match(/https?:\/\/[^\s;]+/) || [""])[0];

const coreDirections = ["Работа и свое дело", "Образование и развитие", "Благоустройство", "Транспорт", "Укрепление и охрана здоровья"];
function practiceWord(count) { const lastTwo = count % 100; const last = count % 10; if (lastTwo >= 11 && lastTwo <= 14) return "практик"; if (last === 1) return "практика"; if (last >= 2 && last <= 4) return "практики"; return "практик"; }
function hasDirection(practice, direction) { return direction.includes("/") ? practice.direction === direction : practice.direction.split("/").map((item) => item.trim()).includes(direction); }
function isRussian(practice) { return String(practice.country || "").trim().toLocaleLowerCase("ru") === "россия"; }
function toColumnIndex(ref) { let out = 0; for (const char of ref.replace(/\d/g, "")) out = out * 26 + char.charCodeAt(0) - 64; return out - 1; }
async function unzipXlsx(buffer) {
  const bytes = new Uint8Array(buffer); const view = new DataView(buffer); let end = -1;
  for (let i = bytes.length - 22; i >= Math.max(0, bytes.length - 65557); i--) if (view.getUint32(i, true) === 0x06054b50) { end = i; break; }
  if (end < 0) throw new Error("Не найден ZIP-каталог XLSX");
  const entries = view.getUint16(end + 10, true); let offset = view.getUint32(end + 16, true); const files = new Map(); const decoder = new TextDecoder("utf-8");
  for (let i = 0; i < entries; i++) {
    if (view.getUint32(offset, true) !== 0x02014b50) throw new Error("Некорректная запись XLSX");
    const method = view.getUint16(offset + 10, true); const compressed = view.getUint32(offset + 20, true); const nameLength = view.getUint16(offset + 28, true); const extraLength = view.getUint16(offset + 30, true); const commentLength = view.getUint16(offset + 32, true); const local = view.getUint32(offset + 42, true); const name = decoder.decode(bytes.slice(offset + 46, offset + 46 + nameLength));
    const localNameLength = view.getUint16(local + 26, true); const localExtraLength = view.getUint16(local + 28, true); const payload = bytes.slice(local + 30 + localNameLength + localExtraLength, local + 30 + localNameLength + localExtraLength + compressed);
    let data; if (method === 0) data = payload; else if (method === 8) data = new Uint8Array(await new Response(new Blob([payload]).stream().pipeThrough(new DecompressionStream("deflate-raw"))).arrayBuffer()); else throw new Error("Неподдерживаемое сжатие XLSX");
    files.set(name, decoder.decode(data)); offset += 46 + nameLength + extraLength + commentLength;
  }
  return files;
}
function parseXlsxText(text) { return new DOMParser().parseFromString(text, "application/xml"); }
function parseXlsxRows(files) {
  const shared = files.get("xl/sharedStrings.xml") ? [...parseXlsxText(files.get("xl/sharedStrings.xml")).querySelectorAll("si")].map((node) => [...node.querySelectorAll("t")].map((t) => t.textContent).join("")) : [];
  const sheetName = [...files.keys()].find((name) => /^xl\/worksheets\/sheet\d+\.xml$/.test(name)); if (!sheetName) throw new Error("В книге не найден лист с данными");
  const rows = [];
  for (const row of parseXlsxText(files.get(sheetName)).querySelectorAll("sheetData > row")) { const values = []; for (const cell of row.querySelectorAll("c")) { const index = toColumnIndex(cell.getAttribute("r") || "A1"); const type = cell.getAttribute("t"); let value = type === "inlineStr" ? cell.querySelector("is")?.textContent || "" : cell.querySelector("v")?.textContent || ""; if (type === "s") value = shared[Number(value)] || ""; values[index] = value; } rows.push(values); }
  const headerIndex = rows.findIndex((row) => row.includes("№")); if (headerIndex < 0) throw new Error("Не найдена строка заголовков"); const headers = rows[headerIndex].map((value) => String(value || "").trim());
  return rows.slice(headerIndex + 1).filter((row) => row[0] !== undefined && String(row[0]).trim()).map((row) => { const source = Object.fromEntries(headers.map((header, index) => [header, String(row[index] || "").trim()])); return { id: source["№"], name: source["Название практики"], country: source["Страна"], region: source["Регион"], direction: source["Направление РКЖ"], factor: source["Фактор РКЖ"], indicator: source["Показатель РКЖ"], audience: source["Целевая аудитория"], problem: source["Проблема"], essence: source["Суть практики"], success: source["Ключевые факторы успеха"], source: source["Источник информации"], years: source["Год(ы) реализации"], budget: source["Оценка стоимости / бюджет реализации"], international: Number(source["№"]) >= 204 }; });
}
async function loadRemotePractices() {
  const metadata = await fetch(`https://cloud-api.yandex.net/v1/disk/public/resources/download?public_key=${encodeURIComponent(YANDEX_PUBLIC_URL)}`); if (!metadata.ok) throw new Error("Не удалось получить ссылку на таблицу"); const { href } = await metadata.json(); if (!href) throw new Error("Не получена ссылка на скачивание"); const file = await fetch(href); if (!file.ok) throw new Error("Не удалось скачать таблицу"); return parseXlsxRows(await unzipXlsx(await file.arrayBuffer()));
}
function populateSelect(id, label, options) { el(id).innerHTML = `<option value="">${label}</option>${options.map((option) => `<option value="${escapeHtml(option)}">${escapeHtml(option)}</option>`).join("")}`; }
function filteredPractices() { const query = state.search.trim().toLocaleLowerCase("ru"); return practices.filter((practice) => { const matches = !query || [practice.name,practice.country,practice.region,practice.problem,practice.essence,practice.factor,practice.indicator].join(" ").toLocaleLowerCase("ru").includes(query); return matches && (!state.direction || hasDirection(practice, state.direction)) && (!state.country || practice.country === state.country) && (!state.factor || practice.factor === state.factor) && (!state.international || !isRussian(practice)); }); }
function makeSummary() { el("summary-grid").innerHTML = coreDirections.map((direction) => { const count = practices.filter((practice) => hasDirection(practice, direction)).length; const style = directionStyles[direction] || { color:"#00aeef" }; return `<button class="summary-card" style="--card-color:${style.color}" data-direction="${escapeHtml(direction)}" type="button"><div class="summary-count">${count}</div><div class="summary-name">${escapeHtml(direction)}</div></button>`; }).join(""); document.querySelectorAll(".summary-card").forEach((button) => button.addEventListener("click", () => { state.direction = button.dataset.direction; el("direction-filter").value = state.direction; state.selectedId = null; render(); document.querySelector(".explorer").scrollIntoView({ behavior:"smooth", block:"start" }); })); }
function detailMarkup(practice) {
  const url = firstUrl(practice.source);
  return `<div class="detail-kicker"><span>${escapeHtml(practice.country)} · ${escapeHtml(practice.region || "уровень не указан")}</span><span>№ ${escapeHtml(practice.id)}</span></div><h3>${escapeHtml(practice.name)}</h3><div class="detail-tags"><span class="tag">${escapeHtml(practice.direction)}</span><span class="tag">${practice.international ? "международная" : "российская"}</span></div><div class="detail-section"><h4>Проблема</h4><p>${escapeHtml(practice.problem)}</p></div><div class="detail-section"><h4>Как устроено решение</h4><p>${escapeHtml(practice.essence)}</p></div><div class="detail-section"><h4>Почему работает</h4><p>${escapeHtml(practice.success)}</p></div><div class="detail-metadata"><div><h4>Целевая аудитория</h4><p>${escapeHtml(practice.audience)}</p></div><div><h4>РКЖ</h4><p>${escapeHtml(practice.factor)}<br><br>${escapeHtml(practice.indicator)}</p></div></div><div class="detail-metadata"><div><h4>Период</h4><p>${escapeHtml(practice.years || "Не указан")}</p></div><div><h4>Бюджет / стоимость</h4><p>${escapeHtml(practice.budget || "В источнике не указано")}</p></div></div>${url ? `<a class="source-link" href="${escapeHtml(url)}" target="_blank" rel="noreferrer">Открыть источник</a>` : ""}`;
}
function detail(practice) { if (!practice) { el("detail-panel").innerHTML = `<div class="detail-empty">Выберите практику,<br>чтобы увидеть<br>управленческую логику.</div>`; return; } const style = directionStyles[practice.direction] || {color:"#00aeef"}; el("detail-panel").style.setProperty("--detail-color",style.color); el("detail-panel").innerHTML = detailMarkup(practice); }
function render() { const visible = filteredPractices(); if (!visible.some((practice) => practice.id === state.selectedId)) state.selectedId = visible[0]?.id || null; const selected = visible.find((practice) => practice.id === state.selectedId); el("results-count").textContent = `${visible.length} ${practiceWord(visible.length)}`; el("active-filter-text").textContent = state.direction || (state.international ? "Международные практики" : "Все направления"); el("practice-list").innerHTML = visible.length ? visible.map((practice) => { const style = directionStyles[practice.direction] || {color:"#00aeef"}; const selectedInline = practice.id === state.selectedId ? `<div class="mobile-detail" style="--detail-color:${style.color}">${detailMarkup(practice)}</div>` : ""; return `<button class="practice-item ${practice.id === state.selectedId ? "active" : ""}" data-id="${escapeHtml(practice.id)}" type="button"><span class="practice-index">${escapeHtml(practice.id)}</span><span><h3>${escapeHtml(practice.name)}</h3><p>${escapeHtml(practice.country)} · ${escapeHtml(practice.region)}</p></span><span class="direction-pill" style="--pill-color:${style.color}">${escapeHtml(practice.direction)}</span></button>${selectedInline}`; }).join("") : `<div class="empty-state">Ничего не найдено. Измените фильтры или поисковый запрос.</div>`; document.querySelectorAll(".practice-item").forEach((button) => button.addEventListener("click", () => { state.selectedId = button.dataset.id; render(); })); detail(selected); }
function resetFilters() { Object.assign(state,{search:"",direction:"",country:"",factor:"",international:false,selectedId:null}); el("search").value=""; el("direction-filter").value=""; el("country-filter").value=""; el("factor-filter").value=""; el("international-toggle").setAttribute("aria-pressed","false"); render(); }
function prepareInterface() { el("header-count").textContent = `${practices.length} ${practiceWord(practices.length)}`; populateSelect("direction-filter","Все направления",coreDirections); populateSelect("country-filter","Все страны",getOptions("country")); populateSelect("factor-filter","Все факторы",getOptions("factor")); makeSummary(); el("search").addEventListener("input",(event) => { state.search=event.target.value; state.selectedId=null; render(); }); ["direction","country","factor"].forEach((key) => el(`${key}-filter`).addEventListener("change",(event) => { state[key]=event.target.value; state.selectedId=null; render(); })); el("international-toggle").addEventListener("click",(event) => { state.international=!state.international; event.currentTarget.setAttribute("aria-pressed",String(state.international)); state.selectedId=null; render(); }); el("reset-filters").addEventListener("click",resetFilters); render(); }
async function refreshData() { try { const remote = await loadRemotePractices(); if (!remote.length) throw new Error("В таблице нет строк"); practices=remote; } catch (error) { practices=window.PRACTICES || []; } state.selectedId=null; prepareInterface(); }
el("reload-data").addEventListener("click",refreshData); refreshData();
el("back-to-top").addEventListener("click", () => window.scrollTo({ top: 0, behavior: "smooth" }));
window.addEventListener("scroll", () => el("back-to-top").classList.toggle("visible", window.scrollY > 520), { passive: true });
